# Generated by Django 4.1.2 on 2022-10-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lyrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(default="", max_length=1000)),
                ("song_id", models.CharField(default="", max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Lyric",
        ),
        migrations.AddField(
            model_name="artiste",
            name="age",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="artiste",
            name="first_name",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AddField(
            model_name="artiste",
            name="last_name",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AddField(
            model_name="song",
            name="artiste_id",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="song",
            name="associated_artiste",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="musicapp.artiste",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="date_released",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AddField(
            model_name="song",
            name="likes",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="title",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AddField(
            model_name="lyrics",
            name="associated_song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="musicapp.song"
            ),
        ),
    ]
